name: gutenberg
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  http: ^0.13.4
  provider: ^6.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/Adventure.svg
    - assets/icons/Back.svg
    - assets/icons/Cancel.svg
    - assets/icons/Drama.svg
    - assets/icons/Fiction.svg
    - assets/icons/History.svg
    - assets/icons/Humour.svg
    - assets/icons/Next.svg
    - assets/icons/Pattern.svg
    - assets/icons/Philosophy.svg
    - assets/icons/Politics.svg
    - assets/icons/Search.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
